name: SwiftyNavigationBar CI
on: 
  push:
    paths: 
      - '**.swift'
      - '**.podspec'

jobs:            
  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.1,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v2            
      - name: iOS
        run: |
          pod install
          xcodebuild -workspace "SwiftyNavigationBar_Demo.xcworkspace" -scheme "SwiftyNavigationBar_Demo" -destination "platform=iOS" clean test | xcpretty
        working-directory: SwiftyNavigationBar_Demo
